---
title: isError
icon: square-f
iconType: solid
---

```ts
function isError<K, T>(error, code): error is T
```

Returns true if the `error` matches an error thrown by quais that matches the error `code`.

In TypeScript environments, this can be used to check that `error` matches an quaisError type, which means the
expected properties will be set.

## Type parameters

| Type parameter |
| :------ |
| `K` *extends* [`ErrorCode`](/sdk/content/type-aliases/ErrorCode) |
| `T` *extends* 
  \| [`UnknownError`](/sdk/content/interfaces/UnknownError)
  \| [`InvalidArgumentError`](/sdk/content/interfaces/InvalidArgumentError)
  \| [`BadDataError`](/sdk/content/interfaces/BadDataError)
  \| [`NotImplementedError`](/sdk/content/interfaces/NotImplementedError)
  \| [`UnsupportedOperationError`](/sdk/content/interfaces/UnsupportedOperationError)
  \| [`NetworkError`](/sdk/content/interfaces/NetworkError)
  \| [`ServerError`](/sdk/content/interfaces/ServerError)
  \| [`TimeoutError`](/sdk/content/interfaces/TimeoutError)
  \| [`CancelledError`](/sdk/content/interfaces/CancelledError)
  \| [`BufferOverrunError`](/sdk/content/interfaces/BufferOverrunError)
  \| [`NumericFaultError`](/sdk/content/interfaces/NumericFaultError)
  \| [`MissingArgumentError`](/sdk/content/interfaces/MissingArgumentError)
  \| [`UnexpectedArgumentError`](/sdk/content/interfaces/UnexpectedArgumentError)
  \| [`CallExceptionError`](/sdk/content/interfaces/CallExceptionError)
  \| [`InsufficientFundsError`](/sdk/content/interfaces/InsufficientFundsError)
  \| [`NonceExpiredError`](/sdk/content/interfaces/NonceExpiredError)
  \| [`ReplacementUnderpricedError`](/sdk/content/interfaces/ReplacementUnderpricedError)
  \| [`TransactionReplacedError`](/sdk/content/interfaces/TransactionReplacedError)
  \| [`ActionRejectedError`](/sdk/content/interfaces/ActionRejectedError) |

## Parameters

| Parameter | Type |
| :------ | :------ |
| `error` | `any` |
| `code` | `K` |

## Returns

`error is T`

## Example

```ts
try {
    // code....
} catch (e) {
    if (isError(e, 'CALL_EXCEPTION')) {
        // The Type Guard has validated this object
        console.log(e.data);
    }
}
```

## See

[ErrorCodes](api:ErrorCode)

## Source

[utils/errors.ts:638](https://github.com/dominant-strategies/quais-6.js/blob/e281b3ca939b91260332b67ef4ba6e8b0a3d4134/src/utils/errors.ts#L638)
